// 內建單字書。欄位：w 單字、ph 音標(KK)、pos 詞性、zh 中文、ex 例句、exZh 例句中譯
const BUILTIN_BOOKS = [
  {
    id: 'lab-songs',
    title: 'Language Lab 01：歌與詩的單字',
    desc: '「英語詞彙記憶法」章節中歌曲與詩的目標單字',
    words: [
      { w: 'pavement', ph: '[ˈpevmənt]', pos: 'n.', zh: '人行道', ex: 'Leaves covered the wet pavement after the storm.', exZh: '暴風雨過後，落葉鋪滿了濕濕的人行道。' },
      { w: 'withered', ph: '[ˈwɪðɚd]', pos: 'adj.', zh: '枯萎的', ex: 'She threw away the withered roses.', exZh: '她把枯萎的玫瑰丟掉了。' },
      { w: 'moan', ph: '[mon]', pos: 'v.', zh: '呻吟；哀鳴', ex: 'The wind moaned through the empty streets.', exZh: '風在空蕩的街道上嗚咽。' },
      { w: 'mutter', ph: '[ˈmʌtɚ]', pos: 'v.', zh: '低聲咕噥', ex: 'He muttered something and walked away.', exZh: '他咕噥了幾句就走開了。' },
      { w: 'gutter', ph: '[ˈgʌtɚ]', pos: 'n./v.', zh: '排水溝；（燭火）搖曳', ex: 'Rainwater ran down the gutter.', exZh: '雨水沿著排水溝流下。' },
      { w: 'fatalistic', ph: '[ˌfetlˈɪstɪk]', pos: 'adj.', zh: '宿命論的', ex: 'He has a fatalistic view of life.', exZh: '他對人生抱持宿命論的看法。' },
      { w: 'weary', ph: '[ˈwɪrɪ]', pos: 'adj.', zh: '疲憊的', ex: 'After the long hike, we were all weary.', exZh: '長途健行後，我們都累壞了。' },
      { w: 'comfort', ph: '[ˈkʌmfɚt]', pos: 'v.', zh: '安慰', ex: 'She comforted her friend after the game.', exZh: '比賽結束後，她安慰她的朋友。' },
      { w: 'ravish', ph: '[ˈrævɪʃ]', pos: 'v.', zh: '使陶醉；使著迷', ex: "The singer's voice ravished the audience.", exZh: '歌手的聲音讓觀眾陶醉。' },
      { w: 'conceit', ph: '[kənˈsit]', pos: 'n.', zh: '巧思；構想；自負', ex: 'The poem is built on a clever conceit.', exZh: '這首詩建立在一個巧妙的構想上。' },
      { w: 'feign', ph: '[fen]', pos: 'v.', zh: '假裝；虛構', ex: 'He feigned illness to skip school.', exZh: '他裝病逃學。' },
      { w: 'mournful', ph: '[ˈmornfəl]', pos: 'adj.', zh: '哀傷的', ex: 'A mournful song played at the end of the film.', exZh: '電影結尾播放著一首哀傷的歌。' },
      { w: 'slumber', ph: '[ˈslʌmbɚ]', pos: 'v./n.', zh: '沉睡；睡眠', ex: 'The baby slumbered peacefully in her arms.', exZh: '嬰兒在她懷裡安穩地睡著。' },
      { w: 'fleeting', ph: '[ˈflitɪŋ]', pos: 'adj.', zh: '稍縱即逝的', ex: 'Summer holidays always feel fleeting.', exZh: '暑假總是感覺一下子就過去了。' },
      { w: 'bivouac', ph: '[ˈbɪvʊˌæk]', pos: 'n.', zh: '臨時營地；露營', ex: 'The climbers set up a bivouac below the peak.', exZh: '登山者在山頂下方搭了臨時營地。' },
      { w: 'sublime', ph: '[səˈblaɪm]', pos: 'adj.', zh: '崇高的；絕妙的', ex: 'The view from the mountain was sublime.', exZh: '山上的景色美得令人讚嘆。' }
    ]
  },
  {
    id: 'jh-core',
    title: '國中會考核心單字',
    desc: '會考高頻字精選，適合國中生每日複習',
    words: [
      { w: 'abroad', ph: '[əˈbrɔd]', pos: 'adv.', zh: '在國外；到國外', ex: 'She wants to study abroad after high school.', exZh: '她高中畢業後想出國讀書。' },
      { w: 'borrow', ph: '[ˈbɑro]', pos: 'v.', zh: '借入；向…借', ex: 'Can I borrow your pen for a minute?', exZh: '我可以借用你的筆一下嗎？' },
      { w: 'careful', ph: '[ˈkɛrfəl]', pos: 'adj.', zh: '小心的；仔細的', ex: 'Be careful when you cross the street.', exZh: '過馬路時要小心。' },
      { w: 'decide', ph: '[dɪˈsaɪd]', pos: 'v.', zh: '決定', ex: 'We decided to go hiking on Sunday.', exZh: '我們決定星期天去健行。' },
      { w: 'enough', ph: '[əˈnʌf]', pos: 'adj.', zh: '足夠的', ex: "We don't have enough time to finish the game.", exZh: '我們沒有足夠的時間把比賽打完。' },
      { w: 'famous', ph: '[ˈfeməs]', pos: 'adj.', zh: '有名的', ex: 'Taipei 101 is a famous building.', exZh: '台北101是一棟有名的建築。' },
      { w: 'guess', ph: '[gɛs]', pos: 'v.', zh: '猜測', ex: "Can you guess what's in the box?", exZh: '你猜得到盒子裡是什麼嗎？' },
      { w: 'habit', ph: '[ˈhæbɪt]', pos: 'n.', zh: '習慣', ex: 'Reading before bed is a good habit.', exZh: '睡前閱讀是個好習慣。' },
      { w: 'important', ph: '[ɪmˈpɔrtnt]', pos: 'adj.', zh: '重要的', ex: 'Sleep is important for your health.', exZh: '睡眠對你的健康很重要。' },
      { w: 'journey', ph: '[ˈdʒɝnɪ]', pos: 'n.', zh: '旅程', ex: 'The journey to Hualien took four hours.', exZh: '去花蓮的旅程花了四個小時。' },
      { w: 'knowledge', ph: '[ˈnɑlɪdʒ]', pos: 'n.', zh: '知識', ex: 'Books give us knowledge about the world.', exZh: '書給我們關於這個世界的知識。' },
      { w: 'lonely', ph: '[ˈlonlɪ]', pos: 'adj.', zh: '寂寞的；孤單的', ex: 'He felt lonely in the new city.', exZh: '他在新的城市裡感到寂寞。' },
      { w: 'message', ph: '[ˈmɛsɪdʒ]', pos: 'n.', zh: '訊息；留言', ex: "I'll send you a message when I get home.", exZh: '我到家時會傳訊息給你。' },
      { w: 'neighbor', ph: '[ˈnebɚ]', pos: 'n.', zh: '鄰居', ex: 'Our neighbor has a friendly dog.', exZh: '我們的鄰居有一隻友善的狗。' },
      { w: 'order', ph: '[ˈɔrdɚ]', pos: 'v.', zh: '點餐；訂購；命令', ex: 'Are you ready to order?', exZh: '您準備好點餐了嗎？' },
      { w: 'practice', ph: '[ˈpræktɪs]', pos: 'v.', zh: '練習', ex: 'I practice the piano every day.', exZh: '我每天練習彈鋼琴。' },
      { w: 'quiet', ph: '[ˈkwaɪət]', pos: 'adj.', zh: '安靜的', ex: 'Please be quiet in the library.', exZh: '在圖書館請保持安靜。' },
      { w: 'remember', ph: '[rɪˈmɛmbɚ]', pos: 'v.', zh: '記得', ex: 'Remember to bring your umbrella.', exZh: '記得帶你的雨傘。' },
      { w: 'surprise', ph: '[sɚˈpraɪz]', pos: 'n.', zh: '驚喜；驚訝', ex: 'The party was a big surprise for Mom.', exZh: '這場派對給了媽媽一個大驚喜。' },
      { w: 'thirsty', ph: '[ˈθɝstɪ]', pos: 'adj.', zh: '口渴的', ex: "I'm thirsty. Can I have some water?", exZh: '我口渴了，可以給我一些水嗎？' },
      { w: 'umbrella', ph: '[ʌmˈbrɛlə]', pos: 'n.', zh: '雨傘', ex: "Don't forget your umbrella. It's going to rain.", exZh: '別忘了你的雨傘，快下雨了。' },
      { w: 'village', ph: '[ˈvɪlɪdʒ]', pos: 'n.', zh: '村莊', ex: 'My grandparents live in a small village.', exZh: '我的祖父母住在一個小村莊裡。' },
      { w: 'weather', ph: '[ˈwɛðɚ]', pos: 'n.', zh: '天氣', ex: 'The weather is hot and sunny today.', exZh: '今天天氣又熱又晴朗。' },
      { w: 'exercise', ph: '[ˈɛksɚˌsaɪz]', pos: 'v.', zh: '運動', ex: 'You should exercise at least three times a week.', exZh: '你應該一週至少運動三次。' },
      { w: 'yell', ph: '[jɛl]', pos: 'v.', zh: '大叫；吼叫', ex: "Don't yell at your little brother.", exZh: '不要對你弟弟大吼。' },
      { w: 'prepare', ph: '[prɪˈpɛr]', pos: 'v.', zh: '準備', ex: 'She is preparing for the exam.', exZh: '她正在準備考試。' },
      { w: 'medicine', ph: '[ˈmɛdəsn]', pos: 'n.', zh: '藥', ex: 'Take this medicine after meals.', exZh: '飯後吃這個藥。' },
      { w: 'invite', ph: '[ɪnˈvaɪt]', pos: 'v.', zh: '邀請', ex: 'Thank you for inviting me to your birthday party.', exZh: '謝謝你邀請我參加你的生日派對。' },
      { w: 'believe', ph: '[bɪˈliv]', pos: 'v.', zh: '相信', ex: 'I believe you can do it.', exZh: '我相信你做得到。' },
      { w: 'different', ph: '[ˈdɪfərənt]', pos: 'adj.', zh: '不同的', ex: 'My sister and I have different hobbies.', exZh: '我和我姊姊有不同的嗜好。' }
    ]
  },
  {
    id: 'sh-gsat',
    title: '學測進階單字',
    desc: '學測 Level 3–5 常考字，附情境例句',
    words: [
      { w: 'abandon', ph: '[əˈbændən]', pos: 'v.', zh: '拋棄；放棄', ex: 'They had to abandon the car in the snow.', exZh: '他們不得不把車丟在雪地裡。' },
      { w: 'accurate', ph: '[ˈækjərɪt]', pos: 'adj.', zh: '準確的', ex: 'The weather report was accurate this time.', exZh: '這次的氣象預報很準確。' },
      { w: 'benefit', ph: '[ˈbɛnəfɪt]', pos: 'n.', zh: '好處；利益', ex: 'Regular exercise has many benefits.', exZh: '規律運動有許多好處。' },
      { w: 'candidate', ph: '[ˈkændəˌdet]', pos: 'n.', zh: '候選人；應徵者', ex: 'There are three candidates for class leader.', exZh: '班長有三位候選人。' },
      { w: 'contribute', ph: '[kənˈtrɪbjut]', pos: 'v.', zh: '貢獻；捐助', ex: 'Everyone contributed ideas to the project.', exZh: '每個人都為這個專題貢獻了點子。' },
      { w: 'convenient', ph: '[kənˈvinjənt]', pos: 'adj.', zh: '方便的', ex: 'Is Friday convenient for you?', exZh: '星期五你方便嗎？' },
      { w: 'decline', ph: '[dɪˈklaɪn]', pos: 'v.', zh: '下降；婉拒', ex: 'The number of students has declined in recent years.', exZh: '近年來學生人數下降了。' },
      { w: 'efficient', ph: '[ɪˈfɪʃənt]', pos: 'adj.', zh: '有效率的', ex: 'This new machine is more efficient.', exZh: '這台新機器更有效率。' },
      { w: 'emphasize', ph: '[ˈɛmfəˌsaɪz]', pos: 'v.', zh: '強調', ex: 'The teacher emphasized the importance of reading.', exZh: '老師強調閱讀的重要性。' },
      { w: 'essential', ph: '[ɪˈsɛnʃəl]', pos: 'adj.', zh: '必要的；不可或缺的', ex: 'Water is essential for all living things.', exZh: '水對所有生物來說都不可或缺。' },
      { w: 'frustrated', ph: '[ˈfrʌstretɪd]', pos: 'adj.', zh: '感到挫折的', ex: 'He felt frustrated when he failed the test again.', exZh: '他再次考試不及格時感到很挫折。' },
      { w: 'generous', ph: '[ˈdʒɛnərəs]', pos: 'adj.', zh: '慷慨的；大方的', ex: 'It was generous of you to share your lunch.', exZh: '你願意分享午餐真是大方。' },
      { w: 'hesitate', ph: '[ˈhɛzəˌtet]', pos: 'v.', zh: '猶豫', ex: "Don't hesitate to ask questions.", exZh: '有問題不要猶豫，儘管問。' },
      { w: 'identify', ph: '[aɪˈdɛntəˌfaɪ]', pos: 'v.', zh: '辨認；識別', ex: 'Can you identify the bird in this photo?', exZh: '你能認出這張照片裡的鳥嗎？' },
      { w: 'influence', ph: '[ˈɪnfluəns]', pos: 'n.', zh: '影響', ex: 'Parents have a strong influence on their children.', exZh: '父母對孩子有很大的影響。' },
      { w: 'maintain', ph: '[menˈten]', pos: 'v.', zh: '維持；保養', ex: "It's hard to maintain a healthy diet.", exZh: '要維持健康的飲食很難。' },
      { w: 'negotiate', ph: '[nɪˈgoʃɪˌet]', pos: 'v.', zh: '協商；談判', ex: 'The two sides negotiated for hours.', exZh: '雙方協商了好幾個小時。' },
      { w: 'obvious', ph: '[ˈɑbvɪəs]', pos: 'adj.', zh: '明顯的', ex: 'The answer seemed obvious to everyone.', exZh: '答案對每個人來說似乎都很明顯。' },
      { w: 'participate', ph: '[pɑrˈtɪsəˌpet]', pos: 'v.', zh: '參加；參與', ex: 'All students are encouraged to participate in the event.', exZh: '鼓勵所有學生參加這個活動。' },
      { w: 'potential', ph: '[pəˈtɛnʃəl]', pos: 'n.', zh: '潛力', ex: 'She has the potential to become a great writer.', exZh: '她有成為偉大作家的潛力。' },
      { w: 'priority', ph: '[praɪˈɔrətɪ]', pos: 'n.', zh: '優先事項', ex: 'Safety is our top priority.', exZh: '安全是我們的首要考量。' },
      { w: 'recognize', ph: '[ˈrɛkəgˌnaɪz]', pos: 'v.', zh: '認出；承認', ex: "I didn't recognize him with his new haircut.", exZh: '他剪了新髮型，我沒認出他。' },
      { w: 'reluctant', ph: '[rɪˈlʌktənt]', pos: 'adj.', zh: '不情願的', ex: 'He was reluctant to admit his mistake.', exZh: '他不情願承認自己的錯誤。' },
      { w: 'sufficient', ph: '[səˈfɪʃənt]', pos: 'adj.', zh: '足夠的', ex: 'Is one hour sufficient to finish the test?', exZh: '一小時足夠寫完考試嗎？' },
      { w: 'tradition', ph: '[trəˈdɪʃən]', pos: 'n.', zh: '傳統', ex: 'Eating mooncakes is a Mid-Autumn tradition.', exZh: '吃月餅是中秋節的傳統。' },
      { w: 'urgent', ph: '[ˈɝdʒənt]', pos: 'adj.', zh: '緊急的', ex: 'I have an urgent message for the manager.', exZh: '我有一則緊急訊息要給經理。' },
      { w: 'vary', ph: '[ˈvɛrɪ]', pos: 'v.', zh: '變化；各有不同', ex: 'Prices vary from store to store.', exZh: '價格因店而異。' },
      { w: 'withdraw', ph: '[wɪðˈdrɔ]', pos: 'v.', zh: '提（款）；撤回', ex: 'I need to withdraw some money from the ATM.', exZh: '我需要從提款機領一些錢。' },
      { w: 'anxious', ph: '[ˈæŋkʃəs]', pos: 'adj.', zh: '焦慮的；渴望的', ex: 'She was anxious about her exam results.', exZh: '她對考試結果感到焦慮。' },
      { w: 'appreciate', ph: '[əˈpriʃɪˌet]', pos: 'v.', zh: '感激；欣賞', ex: 'I really appreciate your help.', exZh: '我真的很感激你的幫忙。' }
    ]
  }
];
