// 內建單字書。欄位：w 單字、ph 音標(KK)、pos 詞性、zh 中文、ex 例句、exZh 例句中譯
const BUILTIN_BOOKS = [
  {
    id: 'lab-songs',
    title: 'Language Lab 01：歌與詩的單字',
    desc: '「英語詞彙記憶法」章節中歌曲與詩的目標單字',
    words: [
      { w: 'pavement', ph: '[ˈpevmənt]', pos: 'n.', zh: '人行道', ex: 'Leaves covered the wet pavement after the storm.', exZh: '暴風雨過後，落葉鋪滿了濕濕的人行道。', col: [['on the pavement', '在人行道上'], ['pavement café', '路邊咖啡座']] },
      { w: 'withered', ph: '[ˈwɪðɚd]', pos: 'adj.', zh: '枯萎的', ex: 'She threw away the withered roses.', exZh: '她把枯萎的玫瑰丟掉了。', col: [['withered leaves', '枯葉'], ['withered flowers', '枯萎的花']] },
      { w: 'moan', ph: '[mon]', pos: 'v.', zh: '呻吟；哀鳴', ex: 'The wind moaned through the empty streets.', exZh: '風在空蕩的街道上嗚咽。', col: [['moan about', '抱怨…'], ['moan in pain', '痛苦地呻吟']] },
      { w: 'mutter', ph: '[ˈmʌtɚ]', pos: 'v.', zh: '低聲咕噥', ex: 'He muttered something and walked away.', exZh: '他咕噥了幾句就走開了。', col: [['mutter to oneself', '喃喃自語'], ['mutter under one\'s breath', '小聲嘀咕']] },
      { w: 'gutter', ph: '[ˈgʌtɚ]', pos: 'n./v.', zh: '排水溝；（燭火）搖曳', ex: 'Rainwater ran down the gutter.', exZh: '雨水沿著排水溝流下。', col: [['in the gutter', '在水溝裡；潦倒'], ['gutter press', '八卦小報']] },
      { w: 'fatalistic', ph: '[ˌfetlˈɪstɪk]', pos: 'adj.', zh: '宿命論的', ex: 'He has a fatalistic view of life.', exZh: '他對人生抱持宿命論的看法。', col: [['fatalistic attitude', '宿命的態度'], ['fatalistic view', '宿命觀']] },
      { w: 'weary', ph: '[ˈwɪrɪ]', pos: 'adj.', zh: '疲憊的', ex: 'After the long hike, we were all weary.', exZh: '長途健行後，我們都累壞了。', col: [['weary of', '厭倦…'], ['weary eyes', '疲倦的雙眼'], ['grow weary', '變得疲憊']] },
      { w: 'comfort', ph: '[ˈkʌmfɚt]', pos: 'v.', zh: '安慰', ex: 'She comforted her friend after the game.', exZh: '比賽結束後，她安慰她的朋友。', col: [['comfort sb', '安慰某人'], ['take comfort in', '從…得到安慰'], ['comfort zone', '舒適圈']] },
      { w: 'ravish', ph: '[ˈrævɪʃ]', pos: 'v.', zh: '使陶醉；使著迷', ex: "The singer's voice ravished the audience.", exZh: '歌手的聲音讓觀眾陶醉。', col: [['be ravished by', '被…迷住']] },
      { w: 'conceit', ph: '[kənˈsit]', pos: 'n.', zh: '巧思；構想；自負', ex: 'The poem is built on a clever conceit.', exZh: '這首詩建立在一個巧妙的構想上。', col: [['full of conceit', '非常自負'], ['poetic conceit', '詩中的巧妙比喻']] },
      { w: 'feign', ph: '[fen]', pos: 'v.', zh: '假裝；虛構', ex: 'He feigned illness to skip school.', exZh: '他裝病逃學。', col: [['feign illness', '裝病'], ['feign surprise', '假裝驚訝'], ['feign ignorance', '裝傻']] },
      { w: 'mournful', ph: '[ˈmornfəl]', pos: 'adj.', zh: '哀傷的', ex: 'A mournful song played at the end of the film.', exZh: '電影結尾播放著一首哀傷的歌。', col: [['mournful voice', '哀傷的聲音'], ['mournful song', '哀歌']] },
      { w: 'slumber', ph: '[ˈslʌmbɚ]', pos: 'v./n.', zh: '沉睡；睡眠', ex: 'The baby slumbered peacefully in her arms.', exZh: '嬰兒在她懷裡安穩地睡著。', col: [['fall into slumber', '陷入沉睡'], ['slumber party', '睡衣派對']] },
      { w: 'fleeting', ph: '[ˈflitɪŋ]', pos: 'adj.', zh: '稍縱即逝的', ex: 'Summer holidays always feel fleeting.', exZh: '暑假總是感覺一下子就過去了。', col: [['fleeting moment', '轉瞬即逝的時刻'], ['fleeting glance', '匆匆一瞥']] },
      { w: 'bivouac', ph: '[ˈbɪvʊˌæk]', pos: 'n.', zh: '臨時營地；露營', ex: 'The climbers set up a bivouac below the peak.', exZh: '登山者在山頂下方搭了臨時營地。', col: [['bivouac site', '臨時營地']] },
      { w: 'sublime', ph: '[səˈblaɪm]', pos: 'adj.', zh: '崇高的；絕妙的', ex: 'The view from the mountain was sublime.', exZh: '山上的景色美得令人讚嘆。', col: [['sublime beauty', '崇高的美'], ['from the sublime to the ridiculous', '從崇高落到荒謬']] }
    ]
  },
  {
    id: 'jh8',
    title: '國中八年級單字',
    desc: '八年級常見主題：旅行、健康、節慶、科技、環境、職業、比賽、友情',
    words: [
      { w: 'trip', ph: '[trɪp]', pos: 'n.', zh: '旅行', ex: 'Have a nice trip!', exZh: '祝你旅途愉快！', col: [['take a trip', '去旅行'], ['school trip', '校外教學'], ['business trip', '出差']] },
      { w: 'ticket', ph: '[ˈtɪkɪt]', pos: 'n.', zh: '票', ex: 'I bought two tickets for the concert.', exZh: '我買了兩張演唱會的票。', col: [['buy a ticket', '買票'], ['train ticket', '火車票'], ['ticket for sth', '…的票']] },
      { w: 'airport', ph: '[ˈɛrˌport]', pos: 'n.', zh: '機場', ex: 'My uncle drove us to the airport.', exZh: '我叔叔開車載我們去機場。', col: [['at the airport', '在機場'], ['go to the airport', '去機場']] },
      { w: 'visit', ph: '[ˈvɪzɪt]', pos: 'v.', zh: '拜訪；參觀', ex: 'We will visit our grandparents this weekend.', exZh: '我們這週末會去拜訪祖父母。', col: [['visit sb', '拜訪某人'], ['visit a museum', '參觀博物館'], ['pay a visit to', '拜訪…']] },
      { w: 'plan', ph: '[plæn]', pos: 'n./v.', zh: '計畫', ex: 'Do you have any plans for the summer vacation?', exZh: '暑假你有什麼計畫嗎？', col: [['make a plan', '訂計畫'], ['plan to V', '計畫做…'], ['plan for', '為…做計畫']] },
      { w: 'healthy', ph: '[ˈhɛlθɪ]', pos: 'adj.', zh: '健康的', ex: 'Eating fruit every day keeps you healthy.', exZh: '每天吃水果讓你保持健康。', col: [['stay healthy', '保持健康'], ['healthy food', '健康的食物'], ['healthy habit', '健康的習慣']] },
      { w: 'fever', ph: '[ˈfivɚ]', pos: 'n.', zh: '發燒', ex: 'She has a fever, so she stays in bed.', exZh: '她發燒了，所以躺在床上休息。', col: [['have a fever', '發燒'], ['high fever', '高燒']] },
      { w: 'rest', ph: '[rɛst]', pos: 'n./v.', zh: '休息', ex: 'You should get some rest.', exZh: '你應該休息一下。', col: [['take a rest', '休息一下'], ['get some rest', '休息'], ['the rest of', '其餘的…']] },
      { w: 'dentist', ph: '[ˈdɛntɪst]', pos: 'n.', zh: '牙醫', ex: 'I go to the dentist twice a year.', exZh: '我一年看兩次牙醫。', col: [['go to the dentist', '去看牙醫'], ['see a dentist', '看牙醫']] },
      { w: 'stomach', ph: '[ˈstʌmək]', pos: 'n.', zh: '胃；肚子', ex: 'I ate too much and my stomach hurts.', exZh: '我吃太多，胃好痛。', col: [['stomachache', '胃痛'], ['on an empty stomach', '空腹']] },
      { w: 'festival', ph: '[ˈfɛstəvl]', pos: 'n.', zh: '節日；節慶', ex: 'Mid-Autumn Festival is my favorite festival.', exZh: '中秋節是我最喜歡的節日。', col: [['Lantern Festival', '元宵節'], ['Dragon Boat Festival', '端午節'], ['music festival', '音樂節']] },
      { w: 'celebrate', ph: '[ˈsɛləˌbret]', pos: 'v.', zh: '慶祝', ex: 'We celebrate Chinese New Year with our family.', exZh: '我們和家人一起慶祝農曆新年。', col: [['celebrate a birthday', '慶生'], ['celebrate with sb', '和某人一起慶祝']] },
      { w: 'gift', ph: '[gɪft]', pos: 'n.', zh: '禮物', ex: 'Thank you for the lovely gift.', exZh: '謝謝你這份可愛的禮物。', col: [['birthday gift', '生日禮物'], ['give sb a gift', '送某人禮物']] },
      { w: 'decorate', ph: '[ˈdɛkəˌret]', pos: 'v.', zh: '裝飾；佈置', ex: 'We decorated the classroom for the party.', exZh: '我們為派對佈置教室。', col: [['decorate A with B', '用 B 裝飾 A'], ['decorate a room', '佈置房間']] },
      { w: 'lantern', ph: '[ˈlæntɚn]', pos: 'n.', zh: '燈籠', ex: 'The children carried paper lanterns at night.', exZh: '孩子們晚上提著紙燈籠。', col: [['paper lantern', '紙燈籠'], ['sky lantern', '天燈']] },
      { w: 'computer', ph: '[kəmˈpjutɚ]', pos: 'n.', zh: '電腦', ex: 'I use the computer to do my homework.', exZh: '我用電腦寫功課。', col: [['use a computer', '用電腦'], ['computer game', '電腦遊戲'], ['on the computer', '在電腦上']] },
      { w: 'internet', ph: '[ˈɪntɚˌnɛt]', pos: 'n.', zh: '網際網路', ex: 'You can find a lot of information on the Internet.', exZh: '你可以在網路上找到很多資訊。', col: [['on the Internet', '在網路上'], ['surf the Internet', '上網']] },
      { w: 'online', ph: '[ˈɑnˌlaɪn]', pos: 'adv.', zh: '在線上；在網路上', ex: 'My sister buys clothes online.', exZh: '我姊姊在網路上買衣服。', col: [['buy sth online', '網購'], ['online class', '線上課程'], ['go online', '上網']] },
      { w: 'download', ph: '[ˈdaʊnˌlod]', pos: 'v.', zh: '下載', ex: 'I downloaded a new app yesterday.', exZh: '我昨天下載了一個新的 app。', col: [['download an app', '下載 app'], ['download a file', '下載檔案']] },
      { w: 'smartphone', ph: '[ˈsmɑrtˌfon]', pos: 'n.', zh: '智慧型手機', ex: 'Many students have their own smartphones.', exZh: '很多學生有自己的智慧型手機。', col: [['use a smartphone', '用智慧型手機'], ['smartphone app', '手機 app']] },
      { w: 'environment', ph: '[ɪnˈvaɪrənmənt]', pos: 'n.', zh: '環境', ex: 'We should protect the environment.', exZh: '我們應該保護環境。', col: [['protect the environment', '保護環境'], ['learning environment', '學習環境']] },
      { w: 'trash', ph: '[træʃ]', pos: 'n.', zh: '垃圾', ex: 'Please don’t throw trash on the street.', exZh: '請不要在街上丟垃圾。', col: [['take out the trash', '倒垃圾'], ['trash can', '垃圾桶'], ['pick up trash', '撿垃圾']] },
      { w: 'recycle', ph: '[riˈsaɪkl]', pos: 'v.', zh: '回收', ex: 'We recycle bottles and paper at school.', exZh: '我們在學校回收瓶子和紙。', col: [['recycle bottles', '回收瓶子'], ['recycling bin', '回收桶']] },
      { w: 'save', ph: '[sev]', pos: 'v.', zh: '節省；拯救', ex: 'Turn off the lights to save energy.', exZh: '關燈來節省能源。', col: [['save energy', '節省能源'], ['save money', '存錢'], ['save water', '省水']] },
      { w: 'pollution', ph: '[pəˈluʃən]', pos: 'n.', zh: '污染', ex: 'Air pollution is a big problem in many cities.', exZh: '空氣污染是許多城市的大問題。', col: [['air pollution', '空氣污染'], ['water pollution', '水污染']] },
      { w: 'dream', ph: '[drim]', pos: 'n.', zh: '夢想；夢', ex: 'My dream is to be a singer.', exZh: '我的夢想是成為歌手。', col: [['dream of', '夢想…'], ['dream come true', '美夢成真'], ['have a dream', '有個夢想']] },
      { w: 'future', ph: '[ˈfjutʃɚ]', pos: 'n.', zh: '未來', ex: 'What do you want to be in the future?', exZh: '你將來想做什麼？', col: [['in the future', '在未來'], ['future plan', '未來的計畫']] },
      { w: 'become', ph: '[bɪˈkʌm]', pos: 'v.', zh: '成為；變得', ex: 'She wants to become a doctor.', exZh: '她想成為醫生。', col: [['become a doctor', '成為醫生'], ['become friends', '變成朋友']] },
      { w: 'engineer', ph: '[ˌɛndʒəˈnɪr]', pos: 'n.', zh: '工程師', ex: 'My mother is an engineer.', exZh: '我媽媽是工程師。', col: [['software engineer', '軟體工程師']] },
      { w: 'nurse', ph: '[nɝs]', pos: 'n.', zh: '護理師；護士', ex: 'The nurse took care of me when I was sick.', exZh: '我生病時，護理師照顧我。', col: [['school nurse', '學校護理師'], ['nurse’s office', '保健室']] },
      { w: 'contest', ph: '[ˈkɑntɛst]', pos: 'n.', zh: '比賽', ex: 'Our class won the singing contest.', exZh: '我們班贏了歌唱比賽。', col: [['singing contest', '歌唱比賽'], ['speech contest', '演講比賽'], ['enter a contest', '參加比賽']] },
      { w: 'team', ph: '[tim]', pos: 'n.', zh: '隊伍', ex: 'Our team has eleven players.', exZh: '我們隊有十一個球員。', col: [['basketball team', '籃球隊'], ['team member', '隊員'], ['on the team', '在隊上']] },
      { w: 'win', ph: '[wɪn]', pos: 'v.', zh: '贏', ex: 'I hope our team will win the game.', exZh: '我希望我們隊會贏得比賽。', col: [['win a game', '贏得比賽'], ['win first prize', '得到首獎']] },
      { w: 'lose', ph: '[luz]', pos: 'v.', zh: '輸；遺失', ex: 'Don’t be sad if you lose.', exZh: '輸了不要難過。', col: [['lose a game', '輸掉比賽'], ['lose weight', '減重'], ['lose one’s way', '迷路']] },
      { w: 'cheer', ph: '[tʃɪr]', pos: 'v.', zh: '歡呼；加油', ex: 'The fans cheered for their team.', exZh: '球迷為他們的隊伍加油。', col: [['cheer for', '為…加油'], ['cheer up', '振作起來']] },
      { w: 'friendship', ph: '[ˈfrɛndʃɪp]', pos: 'n.', zh: '友誼', ex: 'Our friendship is very important to me.', exZh: '我們的友誼對我來說很重要。', col: [['close friendship', '深厚的友誼'], ['make friends', '交朋友']] },
      { w: 'angry', ph: '[ˈæŋgrɪ]', pos: 'adj.', zh: '生氣的', ex: 'Why are you angry with me?', exZh: '你為什麼生我的氣？', col: [['angry with sb', '生某人的氣'], ['get angry', '生氣']] },
      { w: 'worried', ph: '[ˈwɝɪd]', pos: 'adj.', zh: '擔心的', ex: 'Mom was worried about me.', exZh: '媽媽很擔心我。', col: [['worried about', '擔心…'], ['look worried', '看起來很擔心']] },
      { w: 'share', ph: '[ʃɛr]', pos: 'v.', zh: '分享', ex: 'Let’s share the pizza.', exZh: '我們一起分享披薩吧。', col: [['share A with B', '和 B 分享 A'], ['share ideas', '分享想法']] },
      { w: 'excited', ph: '[ɪkˈsaɪtɪd]', pos: 'adj.', zh: '興奮的', ex: 'I’m so excited about the school trip.', exZh: '我對校外教學好興奮。', col: [['excited about', '對…感到興奮'], ['get excited', '變得興奮']] }
    ]
  },
  {
    id: 'jh-core',
    title: '國中會考核心單字',
    desc: '會考高頻字精選，適合國中生每日複習',
    words: [
      { w: 'abroad', ph: '[əˈbrɔd]', pos: 'adv.', zh: '在國外；到國外', ex: 'She wants to study abroad after high school.', exZh: '她高中畢業後想出國讀書。', col: [['study abroad', '出國留學'], ['travel abroad', '出國旅行'], ['go abroad', '出國']] },
      { w: 'borrow', ph: '[ˈbɑro]', pos: 'v.', zh: '借入；向…借', ex: 'Can I borrow your pen for a minute?', exZh: '我可以借用你的筆一下嗎？', col: [['borrow sth from sb', '向某人借某物'], ['borrow money', '借錢'], ['borrow a book', '借書']] },
      { w: 'careful', ph: '[ˈkɛrfəl]', pos: 'adj.', zh: '小心的；仔細的', ex: 'Be careful when you cross the street.', exZh: '過馬路時要小心。', col: [['be careful with', '小心處理…'], ['be careful of', '當心…'], ['careful driver', '謹慎的駕駛']] },
      { w: 'decide', ph: '[dɪˈsaɪd]', pos: 'v.', zh: '決定', ex: 'We decided to go hiking on Sunday.', exZh: '我們決定星期天去健行。', col: [['decide to V', '決定做…'], ['decide on', '決定、選定'], ['hard to decide', '難以決定']] },
      { w: 'enough', ph: '[əˈnʌf]', pos: 'adj.', zh: '足夠的', ex: "We don't have enough time to finish the game.", exZh: '我們沒有足夠的時間把比賽打完。', col: [['enough time', '足夠的時間'], ['enough money', '足夠的錢'], ['big enough', '夠大']] },
      { w: 'famous', ph: '[ˈfeməs]', pos: 'adj.', zh: '有名的', ex: 'Taipei 101 is a famous building.', exZh: '台北101是一棟有名的建築。', col: [['be famous for', '以…聞名'], ['be famous as', '以…身分聞名'], ['world-famous', '世界知名的']] },
      { w: 'guess', ph: '[gɛs]', pos: 'v.', zh: '猜測', ex: "Can you guess what's in the box?", exZh: '你猜得到盒子裡是什麼嗎？', col: [['guess what', '你猜怎麼著'], ['make a guess', '猜一猜'], ['guess right', '猜對']] },
      { w: 'habit', ph: '[ˈhæbɪt]', pos: 'n.', zh: '習慣', ex: 'Reading before bed is a good habit.', exZh: '睡前閱讀是個好習慣。', col: [['good habit', '好習慣'], ['break a habit', '戒掉習慣'], ['be in the habit of', '有…的習慣']] },
      { w: 'important', ph: '[ɪmˈpɔrtnt]', pos: 'adj.', zh: '重要的', ex: 'Sleep is important for your health.', exZh: '睡眠對你的健康很重要。', col: [['important to sb', '對某人很重要'], ['it is important to V', '做…很重要'], ['important role', '重要角色']] },
      { w: 'journey', ph: '[ˈdʒɝnɪ]', pos: 'n.', zh: '旅程', ex: 'The journey to Hualien took four hours.', exZh: '去花蓮的旅程花了四個小時。', col: [['long journey', '長途旅程'], ['make a journey', '去旅行'], ['on a journey', '在旅途中']] },
      { w: 'knowledge', ph: '[ˈnɑlɪdʒ]', pos: 'n.', zh: '知識', ex: 'Books give us knowledge about the world.', exZh: '書給我們關於這個世界的知識。', col: [['general knowledge', '常識'], ['gain knowledge', '獲得知識'], ['to my knowledge', '據我所知']] },
      { w: 'lonely', ph: '[ˈlonlɪ]', pos: 'adj.', zh: '寂寞的；孤單的', ex: 'He felt lonely in the new city.', exZh: '他在新的城市裡感到寂寞。', col: [['feel lonely', '感到寂寞'], ['lonely life', '寂寞的生活']] },
      { w: 'message', ph: '[ˈmɛsɪdʒ]', pos: 'n.', zh: '訊息；留言', ex: "I'll send you a message when I get home.", exZh: '我到家時會傳訊息給你。', col: [['send a message', '傳訊息'], ['leave a message', '留言'], ['get the message', '明白意思']] },
      { w: 'neighbor', ph: '[ˈnebɚ]', pos: 'n.', zh: '鄰居', ex: 'Our neighbor has a friendly dog.', exZh: '我們的鄰居有一隻友善的狗。', col: [['next-door neighbor', '隔壁鄰居'], ['good neighbor', '好鄰居']] },
      { w: 'order', ph: '[ˈɔrdɚ]', pos: 'v.', zh: '點餐；訂購；命令', ex: 'Are you ready to order?', exZh: '您準備好點餐了嗎？', col: [['order food', '點餐'], ['take an order', '幫客人點餐'], ['in order to', '為了']] },
      { w: 'practice', ph: '[ˈpræktɪs]', pos: 'v.', zh: '練習', ex: 'I practice the piano every day.', exZh: '我每天練習彈鋼琴。', col: [['practice V-ing', '練習做…'], ['practice makes perfect', '熟能生巧'], ['in practice', '實際上']] },
      { w: 'quiet', ph: '[ˈkwaɪət]', pos: 'adj.', zh: '安靜的', ex: 'Please be quiet in the library.', exZh: '在圖書館請保持安靜。', col: [['keep quiet', '保持安靜'], ['quiet place', '安靜的地方'], ['be quiet', '安靜']] },
      { w: 'remember', ph: '[rɪˈmɛmbɚ]', pos: 'v.', zh: '記得', ex: 'Remember to bring your umbrella.', exZh: '記得帶你的雨傘。', col: [['remember to V', '記得要去做'], ['remember V-ing', '記得做過'], ['remember sb', '記得某人']] },
      { w: 'surprise', ph: '[sɚˈpraɪz]', pos: 'n.', zh: '驚喜；驚訝', ex: 'The party was a big surprise for Mom.', exZh: '這場派對給了媽媽一個大驚喜。', col: [['in surprise', '驚訝地'], ['to one\'s surprise', '令某人驚訝的是'], ['surprise party', '驚喜派對']] },
      { w: 'thirsty', ph: '[ˈθɝstɪ]', pos: 'adj.', zh: '口渴的', ex: "I'm thirsty. Can I have some water?", exZh: '我口渴了，可以給我一些水嗎？', col: [['feel thirsty', '感到口渴'], ['thirsty for', '渴望…']] },
      { w: 'umbrella', ph: '[ʌmˈbrɛlə]', pos: 'n.', zh: '雨傘', ex: "Don't forget your umbrella. It's going to rain.", exZh: '別忘了你的雨傘，快下雨了。', col: [['open an umbrella', '撐傘'], ['take an umbrella', '帶傘']] },
      { w: 'village', ph: '[ˈvɪlɪdʒ]', pos: 'n.', zh: '村莊', ex: 'My grandparents live in a small village.', exZh: '我的祖父母住在一個小村莊裡。', col: [['small village', '小村莊'], ['village life', '鄉村生活']] },
      { w: 'weather', ph: '[ˈwɛðɚ]', pos: 'n.', zh: '天氣', ex: 'The weather is hot and sunny today.', exZh: '今天天氣又熱又晴朗。', col: [['weather forecast', '天氣預報'], ['bad weather', '壞天氣'], ['weather permitting', '天氣允許的話']] },
      { w: 'exercise', ph: '[ˈɛksɚˌsaɪz]', pos: 'v.', zh: '運動', ex: 'You should exercise at least three times a week.', exZh: '你應該一週至少運動三次。', col: [['do exercise', '做運動'], ['get exercise', '運動'], ['regular exercise', '規律運動']] },
      { w: 'yell', ph: '[jɛl]', pos: 'v.', zh: '大叫；吼叫', ex: "Don't yell at your little brother.", exZh: '不要對你弟弟大吼。', col: [['yell at sb', '對某人吼'], ['yell for help', '大聲呼救']] },
      { w: 'prepare', ph: '[prɪˈpɛr]', pos: 'v.', zh: '準備', ex: 'She is preparing for the exam.', exZh: '她正在準備考試。', col: [['prepare for', '為…做準備'], ['prepare a meal', '準備一餐'], ['be prepared to V', '準備好做…']] },
      { w: 'medicine', ph: '[ˈmɛdəsn]', pos: 'n.', zh: '藥', ex: 'Take this medicine after meals.', exZh: '飯後吃這個藥。', col: [['take medicine', '吃藥'], ['Chinese medicine', '中藥']] },
      { w: 'invite', ph: '[ɪnˈvaɪt]', pos: 'v.', zh: '邀請', ex: 'Thank you for inviting me to your birthday party.', exZh: '謝謝你邀請我參加你的生日派對。', col: [['invite sb to', '邀請某人參加…'], ['invite sb to V', '邀請某人做…']] },
      { w: 'believe', ph: '[bɪˈliv]', pos: 'v.', zh: '相信', ex: 'I believe you can do it.', exZh: '我相信你做得到。', col: [['believe in', '信任；相信…存在'], ['believe it or not', '信不信由你'], ['hard to believe', '難以置信']] },
      { w: 'different', ph: '[ˈdɪfərənt]', pos: 'adj.', zh: '不同的', ex: 'My sister and I have different hobbies.', exZh: '我和我姊姊有不同的嗜好。', col: [['be different from', '與…不同'], ['different kinds of', '各種不同的']] }
    ]
  },
  {
    id: 'sh-gsat',
    title: '學測進階單字',
    desc: '學測 Level 3–5 常考字，附情境例句',
    words: [
      { w: 'abandon', ph: '[əˈbændən]', pos: 'v.', zh: '拋棄；放棄', ex: 'They had to abandon the car in the snow.', exZh: '他們不得不把車丟在雪地裡。', col: [['abandon hope', '放棄希望'], ['abandon a plan', '放棄計畫'], ['abandoned pet', '被棄養的寵物']] },
      { w: 'accurate', ph: '[ˈækjərɪt]', pos: 'adj.', zh: '準確的', ex: 'The weather report was accurate this time.', exZh: '這次的氣象預報很準確。', col: [['accurate information', '正確的資訊'], ['accurate description', '準確的描述']] },
      { w: 'benefit', ph: '[ˈbɛnəfɪt]', pos: 'n.', zh: '好處；利益', ex: 'Regular exercise has many benefits.', exZh: '規律運動有許多好處。', col: [['benefit from', '從…中獲益'], ['for the benefit of', '為了…的利益'], ['health benefits', '對健康的好處']] },
      { w: 'candidate', ph: '[ˈkændəˌdet]', pos: 'n.', zh: '候選人；應徵者', ex: 'There are three candidates for class leader.', exZh: '班長有三位候選人。', col: [['presidential candidate', '總統候選人'], ['job candidate', '求職者'], ['strong candidate', '有力人選']] },
      { w: 'contribute', ph: '[kənˈtrɪbjut]', pos: 'v.', zh: '貢獻；捐助', ex: 'Everyone contributed ideas to the project.', exZh: '每個人都為這個專題貢獻了點子。', col: [['contribute to', '促成；對…有貢獻'], ['contribute money', '捐款'], ['contribute ideas', '貢獻想法']] },
      { w: 'convenient', ph: '[kənˈvinjənt]', pos: 'adj.', zh: '方便的', ex: 'Is Friday convenient for you?', exZh: '星期五你方便嗎？', col: [['convenient for sb', '對某人方便'], ['convenient location', '交通方便的地點'], ['convenience store', '便利商店']] },
      { w: 'decline', ph: '[dɪˈklaɪn]', pos: 'v.', zh: '下降；婉拒', ex: 'The number of students has declined in recent years.', exZh: '近年來學生人數下降了。', col: [['decline an invitation', '婉拒邀請'], ['sharp decline', '急遽下降'], ['in decline', '衰退中']] },
      { w: 'efficient', ph: '[ɪˈfɪʃənt]', pos: 'adj.', zh: '有效率的', ex: 'This new machine is more efficient.', exZh: '這台新機器更有效率。', col: [['energy-efficient', '節能的'], ['efficient use of', '有效運用…']] },
      { w: 'emphasize', ph: '[ˈɛmfəˌsaɪz]', pos: 'v.', zh: '強調', ex: 'The teacher emphasized the importance of reading.', exZh: '老師強調閱讀的重要性。', col: [['emphasize the importance of', '強調…的重要性'], ['emphasize that', '強調…']] },
      { w: 'essential', ph: '[ɪˈsɛnʃəl]', pos: 'adj.', zh: '必要的；不可或缺的', ex: 'Water is essential for all living things.', exZh: '水對所有生物來說都不可或缺。', col: [['essential for', '對…不可或缺'], ['essential part', '必要的部分']] },
      { w: 'frustrated', ph: '[ˈfrʌstretɪd]', pos: 'adj.', zh: '感到挫折的', ex: 'He felt frustrated when he failed the test again.', exZh: '他再次考試不及格時感到很挫折。', col: [['frustrated with', '對…感到挫折'], ['feel frustrated', '感到挫折']] },
      { w: 'generous', ph: '[ˈdʒɛnərəs]', pos: 'adj.', zh: '慷慨的；大方的', ex: 'It was generous of you to share your lunch.', exZh: '你願意分享午餐真是大方。', col: [['generous with', '對…很大方'], ['generous gift', '大方的禮物'], ['generous offer', '慷慨的提議']] },
      { w: 'hesitate', ph: '[ˈhɛzəˌtet]', pos: 'v.', zh: '猶豫', ex: "Don't hesitate to ask questions.", exZh: '有問題不要猶豫，儘管問。', col: [['hesitate to V', '猶豫是否做…'], ['without hesitation', '毫不猶豫']] },
      { w: 'identify', ph: '[aɪˈdɛntəˌfaɪ]', pos: 'v.', zh: '辨認；識別', ex: 'Can you identify the bird in this photo?', exZh: '你能認出這張照片裡的鳥嗎？', col: [['identify with', '認同；產生共鳴'], ['identify A as B', '認定A是B'], ['identify the problem', '找出問題']] },
      { w: 'influence', ph: '[ˈɪnfluəns]', pos: 'n.', zh: '影響', ex: 'Parents have a strong influence on their children.', exZh: '父母對孩子有很大的影響。', col: [['have an influence on', '對…有影響'], ['under the influence of', '受…影響'], ['strong influence', '深遠的影響']] },
      { w: 'maintain', ph: '[menˈten]', pos: 'v.', zh: '維持；保養', ex: "It's hard to maintain a healthy diet.", exZh: '要維持健康的飲食很難。', col: [['maintain a balance', '維持平衡'], ['maintain contact', '保持聯繫'], ['maintain that', '堅稱…']] },
      { w: 'negotiate', ph: '[nɪˈgoʃɪˌet]', pos: 'v.', zh: '協商；談判', ex: 'The two sides negotiated for hours.', exZh: '雙方協商了好幾個小時。', col: [['negotiate with sb', '與某人談判'], ['negotiate a deal', '談成交易'], ['negotiate a price', '議價']] },
      { w: 'obvious', ph: '[ˈɑbvɪəs]', pos: 'adj.', zh: '明顯的', ex: 'The answer seemed obvious to everyone.', exZh: '答案對每個人來說似乎都很明顯。', col: [['obvious reason', '明顯的原因'], ['it is obvious that', '顯然…']] },
      { w: 'participate', ph: '[pɑrˈtɪsəˌpet]', pos: 'v.', zh: '參加；參與', ex: 'All students are encouraged to participate in the event.', exZh: '鼓勵所有學生參加這個活動。', col: [['participate in', '參加'], ['actively participate', '積極參與']] },
      { w: 'potential', ph: '[pəˈtɛnʃəl]', pos: 'n.', zh: '潛力', ex: 'She has the potential to become a great writer.', exZh: '她有成為偉大作家的潛力。', col: [['reach one\'s potential', '發揮潛力'], ['potential risk', '潛在風險'], ['full potential', '全部潛能']] },
      { w: 'priority', ph: '[praɪˈɔrətɪ]', pos: 'n.', zh: '優先事項', ex: 'Safety is our top priority.', exZh: '安全是我們的首要考量。', col: [['top priority', '首要之務'], ['give priority to', '優先處理…'], ['set priorities', '排定優先順序']] },
      { w: 'recognize', ph: '[ˈrɛkəgˌnaɪz]', pos: 'v.', zh: '認出；承認', ex: "I didn't recognize him with his new haircut.", exZh: '他剪了新髮型，我沒認出他。', col: [['recognize sb by', '憑…認出某人'], ['widely recognized', '廣受認可']] },
      { w: 'reluctant', ph: '[rɪˈlʌktənt]', pos: 'adj.', zh: '不情願的', ex: 'He was reluctant to admit his mistake.', exZh: '他不情願承認自己的錯誤。', col: [['reluctant to V', '不願意做…'], ['reluctant agreement', '勉強同意']] },
      { w: 'sufficient', ph: '[səˈfɪʃənt]', pos: 'adj.', zh: '足夠的', ex: 'Is one hour sufficient to finish the test?', exZh: '一小時足夠寫完考試嗎？', col: [['sufficient for', '足以…'], ['sufficient evidence', '充分的證據']] },
      { w: 'tradition', ph: '[trəˈdɪʃən]', pos: 'n.', zh: '傳統', ex: 'Eating mooncakes is a Mid-Autumn tradition.', exZh: '吃月餅是中秋節的傳統。', col: [['follow a tradition', '遵循傳統'], ['break with tradition', '打破傳統'], ['by tradition', '依照傳統']] },
      { w: 'urgent', ph: '[ˈɝdʒənt]', pos: 'adj.', zh: '緊急的', ex: 'I have an urgent message for the manager.', exZh: '我有一則緊急訊息要給經理。', col: [['urgent need', '迫切的需要'], ['urgent matter', '急事'], ['in urgent need of', '急需…']] },
      { w: 'vary', ph: '[ˈvɛrɪ]', pos: 'v.', zh: '變化；各有不同', ex: 'Prices vary from store to store.', exZh: '價格因店而異。', col: [['vary from A to B', '從A到B都不同'], ['vary in', '在…方面不同']] },
      { w: 'withdraw', ph: '[wɪðˈdrɔ]', pos: 'v.', zh: '提（款）；撤回', ex: 'I need to withdraw some money from the ATM.', exZh: '我需要從提款機領一些錢。', col: [['withdraw money', '提款'], ['withdraw from', '退出…'], ['withdraw an offer', '撤回提議']] },
      { w: 'anxious', ph: '[ˈæŋkʃəs]', pos: 'adj.', zh: '焦慮的；渴望的', ex: 'She was anxious about her exam results.', exZh: '她對考試結果感到焦慮。', col: [['anxious about', '為…焦慮'], ['anxious to V', '渴望做…'], ['anxious for', '渴望得到…']] },
      { w: 'appreciate', ph: '[əˈpriʃɪˌet]', pos: 'v.', zh: '感激；欣賞', ex: 'I really appreciate your help.', exZh: '我真的很感激你的幫忙。', col: [['appreciate it', '感激'], ['appreciate V-ing', '感謝做了…'], ['appreciate art', '欣賞藝術']] }
    ]
  }
];
